dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mariadb://localhost:3306/@grails.codegen.projectSnakeCaseName@_dev
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mariadb://localhost:3306/@grails.codegen.projectSnakeCaseName@_test
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mariadb://localhost:3306/@grails.codegen.projectSnakeCaseName@_prod
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
